# ROUNDS
racon_rounds: 2  # Number of Racon rounds to run
pilon_rounds: 4  # Number of Pilon rounds to run

# DATA
assembly: data/assembly.fasta  # Path to original assembly
nanopore: data/nanopore_reads_combined.fastq.gz  # Path to Nanopore reads
illumina:
    R1: data/illumina_reads_L001_R1.fastq.gz  # Path to Illumina R1 reads
    R2: data/illumina_reads_L001_R2.fastq.gz  # Path to Illumina R2 reads

# RESOURCES
minimap2:
    threads: 16
    memory: 64000
    runtime: '1-00:00:00'
racon:
    threads: 16
    memory: 64000
    runtime: '2-00:00:00'
bwa:
    threads: 16
    memory: 64000
    runtime: '2-00:00:00'
pilon:
    threads: 16
    memory: 256000
    runtime: '2-00:00:00'
